//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int IDState { get; set; }
        public int IDCategory { get; set; }
        public int IDUser { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public double StartPrice { get; set; }
        public Nullable<double> EndPrice { get; set; }
        public bool Active { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<int> AuctedUser { get; set; }
        public string Coin { get; set; }
        public string Specification { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual State State { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
